### ISSUE TITLE
Brand Classification Project

### ISSUE THREAD

**Issue by NEERAJAP2001** [CoinShift-Imaging/CoinShift-Imaging-Box#108]
Create a Car Brand Classification Project
Tasks:

* Uses Deep learning to detect car brands
* I'm assuming to solve this using resnet50( transfer learning ) but let's see how it goes.
* Dataset consists of Images of 3 different brands ( I'll give the dataset for download in a separate folder)

I'd Like to work on this issue as part of the GSSOC-21

**Comment by NEERAJAP2001** [comment]
@rajpratyush  @Rishikeshrajrxl  any updates can I work on this?

**Comment by DARK-art108** [comment]
@NEERAJAP2001 please go ahead!
