### ISSUE TITLE
add all contributors bot 

### ISSUE THREAD

**Issue by kcoder63** [CoinShift-Imaging/CoinShift-Imaging-Box#13]
add all contributors bot to display the contributors of this project on README

**Comment by DARK-art108** [comment]
Please Go Ahead!! @kcoder63

**Comment by kcoder63** [comment]
it needs to be installed by the project maintainer, I dont have access for it

**Comment by DARK-art108** [comment]
Thanks for Getting this awesome Idea @kcoder63 :)
