### ISSUE TITLE
Mask Detection

### ISSUE THREAD

**Issue by sudipg4112001** [CoinShift-Imaging/CoinShift-Imaging-Box#2]
I would like to add a project for mask detection. To be more precise, I would use datasets which contains multiple images and would detect whether the person is wearing mask or not. Then, determine the total number of person wearing and not wearing  mask.
I am a participant of GSSOC'21

**Comment by DARK-art108** [comment]
Buddy Come to discussion forums first we will discusss and then work upon it @sudipg4112001

**Comment by sudipg4112001** [comment]
Okay..!! Please provide me the link

**Comment by DARK-art108** [comment]
Yeah buddy see after the pr tab you will find a tab.of discussions come their

**Comment by sudipg4112001** [comment]
Yeah, I have started a discussion there.. let's start

**Comment by sudipg4112001** [comment]
Assign me this issue. So, that I can make the PR

**Comment by sudipg4112001** [comment]
Hey..!! Please assign so I can start we had discussions related to this at the discussion forum #4

**Comment by ritikasharma99** [comment]
Hi I am GSSOC participant. I would like to work on this issue. Can you please assign it to me?

**Comment by sudipg4112001** [comment]
This issue is not assigned till now

**Comment by sudipg4112001** [comment]
Thanks
