### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by Dhanush2612** [CoinShift-Imaging/CoinShift-Imaging-Box#21]
Python programs to capture a user's face and generate dataset. Then detect and recognize the user's face by using opencv.

**Comment by Dhanush2612** [comment]
Please assign me this issue if its worth adding in this repo.

**Comment by Rishikeshrajrxl** [comment]
@dhanush2612 , go ahead with this issue and don't forget to add a Gif to the ReadMe.md file.

**Comment by aqua0** [comment]
Can i also work on this issue?

If yes please assign this to me as well.

**Comment by DARK-art108** [comment]
@aqua0 go-ahead!! :)

**Comment by DARK-art108** [comment]
@aqua0 @Dhanush2612 We will merge the PR after reviewing it, so go ahead and raise the PR.

**Comment by aqua0** [comment]
Thank you @DARK-art108

**Comment by aqua0** [comment]
@DARK-art108 Should we do this separately or together sir?
If yes how can i get in touch with @Dhanush2612 .
I am a gssoc'21 participant.

**Comment by DARK-art108** [comment]
you should do separately @aqua0

**Comment by prathimacode-hub** [comment]
Hey, I'm a GSSOC21 participant. I would like to work on this issue. Can you assign it to me?

**Comment by aqua0** [comment]
@DARK-art108 I am done with the recognition part working on the first part now

**Comment by Dhanush2612** [comment]
@DARK-art108 I am done with face recognition part, all I have to do is create readme file. I will complete my PR tomorrow.
