### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [CoinShift-Imaging/CoinShift-Imaging-Box#23]
hey I would like to add the following on contributing.md
1. Update local and forked repo as changes are made in the upstream
2. Squashing the commits into one single commit for easy merging
I would like to do this under GSSOC'21

**Comment by DARK-art108** [comment]
Go Ahead @khareyash05

**Comment by DARK-art108** [comment]
Thanks for Contributing :)
