### ISSUE TITLE
ELMo word vectors

### ISSUE THREAD

**Issue by JadeMaveric** [CoinShift-Imaging/CoinShift-Imaging-Box#25]
Hello, I noticed the ELMo checkbox was unticked in the README. I've been working with ELMo and would like to contribute (as part of gssoc21).
What is required for a successful submission, an example notebook where it is used?

**Comment by DARK-art108** [comment]
Yeah we have opened that working with Elmo task a long back but we don't need it currently, if you can build a model for filling the masked word using Roberta [Hugging face] it would be nice

**Comment by JadeMaveric** [comment]
Hey @DARK-art108 I've been working on the [notebook](https://www.kaggle.com/juliusalphonso/filling-in-masked-words-with-roberta). Please let me know if I should add anything more, like fine tuning the model.

**Comment by DARK-art108** [comment]
Awesome work :) Please raise PR when it is done :)

**Comment by DARK-art108** [comment]
@JadeMaveric

**Comment by JadeMaveric** [comment]
@DARK-art108 do you think it's fine in its current state? Or should add fine tuning?

**Comment by DARK-art108** [comment]
It would be better if you add fine tuning on some dataset. :) @JadeMaveric
