### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by arnab031** [CoinShift-Imaging/CoinShift-Imaging-Box#32]
**Describe the bug**
Model name is wrong under Classification Model's 

**To Reproduce**
1. Go to 'https://github.com/CoinShift-Imaging/CoinShift-Imaging-Box'
2. Click on 'Readme.md'
3. Scroll down to 'Classification Model's'

**Expected behavior**
Model name should be resnet18

**Screenshots**
![Screenshot 2021-03-14 194247](https://user-images.githubusercontent.com/51916075/111071846-10011c80-84fe-11eb-9418-d2b69e58e5ce.png)

**Comment by DARK-art108** [comment]
@arnab031 go ahead :)
