### ISSUE TITLE
Implementing GPT1 and GPT2

### ISSUE THREAD

**Issue by kad99kev** [CoinShift-Imaging/CoinShift-Imaging-Box#34]
Hello!

Under the NLP Models, I noticed that GPT1 and GPT2 are unticked. Do you have a specific use in mind for these models? I would like to work with them as part of GSSOC 2021. Thanks!

**Comment by DARK-art108** [comment]
Yeah please do Text Generation using GPT2 :) @kad99kev

**Comment by kad99kev** [comment]
Would you like me to fine-tune it on any particular dataset or only use the pretrained model?

**Comment by DARK-art108** [comment]
Fine-tuning would be good on any dataset @kad99kev
