### ISSUE TITLE
Implementing GAN and CGAN architecture

### ISSUE THREAD

**Issue by ELITA04** [CoinShift-Imaging/CoinShift-Imaging-Box#38]
Hello, I am a GSSOC'21 participant and I want add the GAN and CGAN architectures trained on MNIST data in the folder https://github.com/CoinShift-Imaging/CoinShift-Imaging-Box/tree/main/GANS.

I will add the notebooks and a readme explaining the same.

Could you please assign it to me?

**Comment by DARK-art108** [comment]
Please Go ahead @ELITA04 :)
