### ISSUE TITLE
Classifying imagenet images using DL

### ISSUE THREAD

**Issue by NEERAJAP2001** [CoinShift-Imaging/CoinShift-Imaging-Box#50]
Tasks Include :

Create a Vgg-19 Model for classifying imagenet images

Create a simple web app with Flask and Html/CSS/Js

Upload an image to predict the class of the image.

Dataset-[Here](https://www.tensorflow.org/datasets/catalog/imagenet2012)

The dataset will be loaded in the code itself, We do not require any manual downloading as it's huge around 15GB.

It has over 200 classes with 100k+ images.
Once The application is done all you need to do is access the web app ( No training as I will be saving the model)

I'd like to work on this as part of the GSSOC-21.
Thanks

**Comment by NEERAJAP2001** [comment]
@Rishikeshrajrxl If you think this issue is accurate enough, I can start working on it.
Thanks

**Comment by DARK-art108** [comment]
Please go ahead @NEERAJAP2001 Make sure you add this whole thing into a folder and then add this folder into a classification folder[already present in repo]  :) also push some images of dataset :)
