### ISSUE TITLE
Brand Classification using DL

### ISSUE THREAD

**Issue by NEERAJAP2001** [CoinShift-Imaging/CoinShift-Imaging-Box#59]
Create a Car Brand Classification Project 
Tasks:
* Uses Deep learning to detect car brands
* I'm assuming to solve this using resnet50( transfer learning ) but let's see how it goes.
* Dataset consists of  Images of 3 different brands ( I'll give the dataset  for download in a separate folder)
* Add flask backend for web app

It will be added as part of [Folder](https://github.com/CoinShift-Imaging/CoinShift-Imaging-Box/tree/main/Classification_Zoo) 

I'd Like to work on this issue as part of GSSOC-21.

**Comment by NEERAJAP2001** [comment]
@DARK-art108 if you think this issue is accurate enough, then I can start working.
Thoughts?

**Comment by DARK-art108** [comment]
@NEERAJAP2001 Go ahead :)
