### ISSUE TITLE
Automatic Number Plate Detection using YOLO and Google Tesseract

### ISSUE THREAD

**Issue by prithwirajmitra2001** [CoinShift-Imaging/CoinShift-Imaging-Box#64]
Would like to work on this issue using either in google colab or kaggle notebooks for better use for everyone.
Please assign me this project as part of GSSOC'21

**Comment by Rishikeshrajrxl** [comment]
@prithwirajmitra2001 go ahead...

**Comment by DARK-art108** [comment]
Any Updates @prithwirajmitra2001

**Comment by prithwirajmitra2001** [comment]
Facing problem with push project

**Comment by prithwirajmitra2001** [comment]
@DARK-art108 
Please check PR #82
