### ISSUE TITLE
New Project Idea : Human Emotion detection

### ISSUE THREAD

**Issue by AM1CODES** [CoinShift-Imaging/CoinShift-Imaging-Box#65]
Hey, so i am a little new to the project and was not exactly sure if the addition that i wished to make went hand in hand with the overall goal of this project but a few days earlier i was working on a project which required me to detect human emotions. The model was built using the Kaggle notebooks and the data set that i used was FER2013 competition data. So it would be great if you could let me know if i can work on making that a part of this project. 

If you would like any more information from my end, please let me know. I am a GSSoC participant.

**Comment by sudipg4112001** [comment]
I want to work on this issues.

**Comment by Rishikeshrajrxl** [comment]
@sudipg4112001, go ahead

**Comment by Rishikeshrajrxl** [comment]
@AM1CODES, Do you want to complete this? Let me know.

**Comment by sudipg4112001** [comment]
> @AM1CODES, Do you want to complete this? Let me know.

What should I make the PR or wait ??

**Comment by AM1CODES** [comment]
> @AM1CODES, Do you want to complete this? Let me know.

@Rishikeshrajrxl Yea i would like to work on it. I had created the issue as i wanted to work on it.

**Comment by Rishikeshrajrxl** [comment]
@AM1CODES, @sudipg4112001, You both will be doing this issue individually. and after submission, both will get the points

**Comment by AM1CODES** [comment]
Okay. I will keep you updated on my progress.

**Comment by sudipg4112001** [comment]
> @AM1CODES, @sudipg4112001, You both will be doing this issue individually. and after submission, both will get the points

Okay..

**Comment by AM1CODES** [comment]
@Rishikeshrajrxl I haven't made the PR yet, so will there be an problem? because this issue has been closed and you allowed both of us to PR for this issue.
