### ISSUE TITLE
Grammatical errors in the Readme file

### ISSUE THREAD

**Issue by anirudhsai20** [CoinShift-Imaging/CoinShift-Imaging-Box#66]
There are a lot of grammatical errors in the Readme file that needs correction.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by Rishikeshrajrxl** [comment]
@anirudhsai20, please specify the Readme file having error.

**Comment by anirudhsai20** [comment]
This file : https://github.com/CoinShift-Imaging/CoinShift-Imaging-Box#readme (The main Readme file)

**Comment by Divya871** [comment]
Hi,please assign this issue to me under GSSOC.Thanks.

**Comment by Rishikeshrajrxl** [comment]
> This file : https://github.com/CoinShift-Imaging/CoinShift-Imaging-Box#readme (The main Readme file)

@anirudhsai20, go ahead.

**Comment by PragatiBhat** [comment]
I am  gssco21 participant can you please assign this to me?
