### ISSUE TITLE
Template matching

### ISSUE THREAD

**Issue by sudipg4112001** [CoinShift-Imaging/CoinShift-Imaging-Box#67]
I would like to add a project for template matching. One template will be taken and will be checked wheather it is in the input image.

**Comment by sudipg4112001** [comment]
Please assign

**Comment by Rishikeshrajrxl** [comment]
@sudipg4112001, please specify the kind  of template.

**Comment by sudipg4112001** [comment]
> @sudipg4112001, please specify the kind of template.

One small image as a template ( This will be part of the original image), then check wheather the template is available in the original image or not

**Comment by Rishikeshrajrxl** [comment]
@sudipg4112001 , go ahead
