### ISSUE TITLE
Blurring face

### ISSUE THREAD

**Issue by sudipg4112001** [CoinShift-Imaging/CoinShift-Imaging-Box#72]
I would like to add a project for blurring face. Here, I would detect face and then blur it.

**Comment by Rishikeshrajrxl** [comment]
@sudipg4112001, explain the algorithm you will be using.

**Comment by sudipg4112001** [comment]
> @sudipg4112001, explain the algorithm you will be using.

 The first step is to perform face detection. In this case, I will use Deep Learning Face Detection of OpenCV. After the face is detected, the ROI is extracted. Then various blurring techniques like Gaussian Blur and Pixelated Blur are applied. The last step involves adding the blurred face to the original image.

Technologies Used
OpenCV, Python 3, OneAPI.

**Comment by sudipg4112001** [comment]
Please mention whether to upload .py file or .ipyb file if this issue is assigned to me

**Comment by Rishikeshrajrxl** [comment]
> Please mention whether to upload .py file or .ipyb file if this issue is assigned to me

You can upload  . py file.

**Comment by Rishikeshrajrxl** [comment]
@sudipg4112001, go ahead
