### ISSUE TITLE
FACE_EYE_DETECTION

### ISSUE THREAD

**Issue by anubhav201241** [CoinShift-Imaging/CoinShift-Imaging-Box#75]
Hi, I'm a Gssoc'21 Participant I would love to contribute to your  project
I want to contribute the face_detection part to your repository in which I would like to add the face, eye, and nose detection part with the help of open-cv and python.

@Rishikeshrajrxl   Kindly Please assign this part to me.

**Comment by Rishikeshrajrxl** [comment]
@anubhav201241, go ahead

**Comment by anubhav201241** [comment]
Thank you sir :))

**Comment by DARK-art108** [comment]
Any Updates!! :) @anubhav201241

**Comment by anubhav201241** [comment]
Yes sir sorry for delay :)

**Comment by anubhav201241** [comment]
@Rishikeshrajrxl Please review it

**Comment by anubhav201241** [comment]
> Any Updates!! :) @anubhav201241

please review it
