### ISSUE TITLE
Helmet Detection using TFOD/Faster-RCNN

### ISSUE THREAD

**Issue by DARK-art108** [CoinShift-Imaging/CoinShift-Imaging-Box#88]
Detect Helmet from real-time traffic videos.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Rishikeshrajrxl** [comment]
@AshuKV  go ahead

**Comment by subhangi2731** [comment]
@DARK-art108 @Rishikeshrajrxl can I work on this please assign me
