### ISSUE TITLE
Pose Detection using OpenCV

### ISSUE THREAD

**Issue by DARK-art108** [CoinShift-Imaging/CoinShift-Imaging-Box#89]
Detect human pose using opencv

**Comment by noviicee** [comment]
I would like to take this up!!

**Comment by ainy-123** [comment]
I am GSSoC'21 participant. I want to work on this issue.
I have worked with opencv, I can raise the PR on the same day of issue assignment. 
Will you please assign this to me?
> Detect human pose using opencv

**Comment by rajpratyush** [comment]
@ainy-123 since @noviicee did not commented after 3 days. You can take up the issue

**Comment by noviicee** [comment]
> @ainy-123 since @noviicee did not commented after 3 days. You can take up the issue

What did I need to comment?
I already asked if I could take it up and was waiting for it to get assigned.

**Comment by ainy-123** [comment]
> @ainy-123 since @noviicee did not commented after 3 days. You can take up the issue

thanks for assigning.

**Comment by noviicee** [comment]
> > @ainy-123 since @noviicee did not commented after 3 days. You can take up the issue
> 
> thanks for assigning.

@ainy-123 
I guess there has been a confusion regarding this issue so I request you to wait until the confusion is sorted out :)

**Comment by rajpratyush** [comment]
sorry for this confusion @ainy-123 would you like up this issue instead #102

**Comment by ainy-123** [comment]
> sorry for this confusion @ainy-123 would you like up this issue instead #102

okay. No issues. I will work on #102 .
