### ISSUE TITLE
addition of code of conduct file

### ISSUE THREAD

**Issue by Sloth-Panda** [CoinShift-Imaging/CoinShift-Imaging-Box#9]
There is no code of conduct file so would like to add one please assign it to me @DARK-art108 
please assign it to me under gssoc'21

**Comment by Sloth-Panda** [comment]
@DARK-art108 is not it required?

**Comment by DARK-art108** [comment]
I am handling that feature so I have closed it,I have assigned one issue you can work over it.@Sloth-Panda
