### ISSUE TITLE
Next word prediction using LSTM and BERT

### ISSUE THREAD

**Issue by Aparna-Sakshi** [CoinShift-Imaging/CoinShift-Imaging-Box#93]
**Description**
Given a sequence of words, next k words will be predicted using 
1) character-based LSTM models
2) word-based LSTM models
3) Transformer-based language model (i.e)BERT

After which I'll compare the performance of these models.
I am a GSSOC-21 participant, kindly assign this issue to me.

**Comment by Rishikeshrajrxl** [comment]
@Aparna-Sakshi  go ahead.

**Comment by Aparna-Sakshi** [comment]
I have made a pull request. Here is the link to it: https://github.com/CoinShift-Imaging/CoinShift-Imaging-Box/pull/94
